from typing import Protocol

class Subscriber(Protocol):
    @property
    def user_id(self) -> str | None: ...
    @property
    def username(self) -> str | None: ...
    def send(self, payload: dict) -> None: ...
