services:
  name-server:
    build: ./server
    command: python -m Pyro5.nameserver --host 0.0.0.0 --port 9090
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "9090:9090"
    networks:
      hexworld:
        ipv4_address: 10.1.0.2

  server-rmi:
    init: true
    build: ./server
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      DATABASE_PATH: /app/data/hexworld.db
      NAME_SERVER_ADDRESS: name-server:9090
      SERVER_ADDRESS: 0.0.0.0:9091
      PUBLIC_ADDRESS: 127.0.0.1:9091
      PYTHONUNBUFFERED: 1
    ports:
      - "9091:9091"
    volumes:
      - ./server:/app
    depends_on:
      - name-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      hexworld:
        ipv4_address: 10.1.0.3

networks:
  hexworld:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
