services:
  server:
    init: true
    build: ./server
    ports:
      - "5000:5000"
    environment:
      DATABASE_PATH: /app/data/hexworld.db
      SERVER_ADDRESS: 0.0.0.0:5000
      PYTHONUNBUFFERED: 1
    volumes:
      - ./server:/app
    networks:
      hexworld:
        ipv4_address: 10.1.0.2

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - server
    networks:
      hexworld:
        ipv4_address: 10.1.0.3

networks:
  hexworld:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
