from typing import Protocol

class ClientSession(Protocol):
    @property
    def user_id(self) -> str | None: ...

    @property
    def username(self) -> str | None: ...

    def bind_user(self, user_id: str, username: str) -> None: ...

    def subscribe(self, map_id: str) -> None: ...

    def unsubscribe(self, map_id: str) -> None: ...

    def enter_presence(self, map_id: str) -> bool: ...

    def leave_presence(self, map_id: str) -> bool: ...

    def send(self, payload: dict) -> None: ...
