PANEL_MARGIN = 12
PANEL_MIN_H = 200
SIDE_PANEL_W = 400
RIGHT_COLUMN_GAP = 12
MINIMAP_H = 220

MEMBERS_SCROLL_THRESHOLD = 5
MEMBERS_VISIBLE_ROWS = 4
MEMBERS_ROW_H = 26
MEMBERS_ROW_GAP = 5
MEMBERS_BAR_MAX_W = 400
