BTN_TOOLBAR_W = 120
BTN_TOOLBAR_H = 46

BTN_COMPACT_W = 100
BTN_COMPACT_H = 40

BTN_PRIMARY = "primary"
BTN_SECONDARY = "secondary"
BTN_GHOST = "ghost"
BTN_GHOST_COMPACT = "ghostCompact"
BTN_DANGER = "danger"
BTN_ACCENT = "accent"
BTN_MAP_CARD_OPEN = "mapCardOpen"
BTN_MAP_CARD_GHOST = "mapCardGhost"
BTN_MAP_CARD_DANGER = "mapCardDanger"

LABEL_OPEN_MAP = "Open"
LABEL_CLOSE_MAP = "Close"

CARD_WIDTH = 360

MAP_CARD_WIDTH = 360
MAP_CARD_MARGIN_H = 16
MAP_CARD_ACTION_GAP = 6

CARD_MARGINS = (32, 22, 32, 28)
CARD_SPACING = 10
